account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='unfollow'),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='update'),
    path('post/create/', views.PostCreateView.as_view(), name='create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

templates/inc/messages.html
{% if messages %}
    {% for messages in messages %}
        <p class="alert alert-{{messages.tags}}">{{ messages }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'account:profile' request.user.id %}">Profile</a>
        <a class="nav-link active" href="{% url 'account:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link active" href="{% url 'account:register' %}">Register</a>
        <a class="nav-link active" href="{% url 'account:login' %}">Login</a>
        {% endif %}
      </div>
    </div>
</nav>